add version check step

diff --git a/.github/workflows/verify-version.yaml b/.github/workflows/verify-version.yaml
--- a/.github/workflows/verify-version.yaml
+++ b/.github/workflows/verify-version.yaml
@@ -38,3 +38,18 @@ jobs:
           java-version: 17
       - id: get-version
         run: echo "version=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
+  ensure-new-version:
+    runs-on: ubuntu-latest
+    needs: [get-target-project-version, get-source-project-version]
+    steps:
+      - name: Compare
+        run: |
+          TARGET="${{ needs.get-target-project-version.steps.outputs.project-version }}"
+          SOURCE="${{ needs.get-source-project-version.steps.outputs.project-version }}"
+          if [ "$TARGET" == "$SOURCE" ]; then
+            echo "Failure: Project versions should not remain the same on merging to main"
+            exit 1
+          else
+            echo "Success: Project version differs from main"
+            exit 0
+          fi
